import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import data from '../data.json';
import { calculateRevenueByCustomerType } from '../utils/dataProcessing';
import type { Order } from '../types/types';

export function RevenueByCustomerType() {
	const revenue = calculateRevenueByCustomerType(data.orders as Order[]);
	const options = {
		chart: {
			type: 'pie',
		},
		title: {
			text: 'Revenue generated by Customer (Type)',
		},
		tooltip: {
			pointFormat: '{point.percentage:.1f}%',
		},
		series: [
			{
				name: 'Revenue',
				data: [
					{ name: 'Returning', y: revenue.returning },
					{ name: 'New', y: revenue.new },
				],
			},
		],
	};
	return <HighchartsReact highcharts={Highcharts} options={options} />;
}
